version: "3.9"

services:
  bot:
    build:
      context: .
      args:
        NODE_VERSION: 17
        TINI_VERSION: v0.19.0
    container_name: valorantbro
    image: valorantbro
    ports:
      - 8080
    volumes:
      - ./.env:/home/node/.env:ro
